apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: devops-expensy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 160180/devopsexpensy_backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8706
          env:
            - name: DATABASE_URI
              value: "mongodb://root:example@mongo:27017"
            - name: REDIS_HOST      # ✅ NUEVA variable
              value: "redis-service" # Nombre del servicio de Redis
            - name: REDIS_PORT      # ✅ NUEVA variable  
              value: "6379"         # Puerto de Redis
            - name: REDIS_PASSWORD  # ✅ NUEVA variable
              value: "someredispassword" # Password de Redis