# .github/workflows/ci.yml
name: CI - Expensy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      IMAGE_NAME_BACKEND: ivangilcar/expensy-backend
      IMAGE_NAME_FRONTEND: ivangilcar/expensy-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build backend Docker image
        run: |
          docker build -t $IMAGE_NAME_BACKEND:latest ./expensy_backend
          docker push $IMAGE_NAME_BACKEND:latest

      - name: Build frontend Docker image
        run: |
          docker build -t $IMAGE_NAME_FRONTEND:latest ./expensy_frontend
          docker push $IMAGE_NAME_FRONTEND:latest

      - name: Run backend tests
        run: |
          docker run --rm $IMAGE_NAME_BACKEND:latest npm test

      - name: Run frontend tests
        run: |
          docker run --rm $IMAGE_NAME_FRONTEND:latest npm test
